### ISSUE TITLE
Tool unexecutable

### ISSUE THREAD

**Issue by longlin58** [timonbldw/GoogleDriveOrphanFixer#1]
Hey, not sure if you are still working on the tool, but ive downloaded the tool and tried executing googledriveorphanfixer, but nothing poped up. it would be great if you can get back to me on it.

**Comment by timonbldw** [comment]
Hi @longlin58,
it's very likely that you have not installed the .NET Core 3.1 Runtime on your system. I must admit, I probably should have used .NET Framework instead, since that is probably already installed on your system. I'll see if I have time to recompile it tonight.

Until then, to verify that the issue truly is the missing runtime you can open the cmd or powershell, navigate into the folder and try to execute `GoogleDriveOrphanFixer.exe` in the command prompt. If the runtime is missing, it will return something like this:
```
C:\Users\XY\Desktop\GoogleDriveOrphanFixer> .\GoogleDriveOrphanFixer.exe

A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\XY\Desktop\GoogleDriveOrphanFixer\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
 ```

If that is the case, simply install .NET Core 3.1. [Here](https://download.visualstudio.microsoft.com/download/pr/aa240732-82d7-4bd1-9701-e4014d7dc735/41a460f5e9c343f7b9207f64ab0e4c90/windowsdesktop-runtime-3.1.18-win-x64.exe
) is a direct link to the latest runtime.

**Comment by longlin58** [comment]
That fixed the issue, I probably should have read the requirements properly too. My bad. Thanks for such a fast reply.
